name = "GeoClustering"
uuid = "1fabc0cd-eb6e-40ea-98cd-762b8100f2e3"
authors = ["RohitRathore1"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
